# -*- coding: UTF-8 -*-

import lldb
import util


def __lldb_init_module(debugger, internal_dict):
    debugger.HandleCommand(
        'command script add -h "" -f '
        'ls.handle_ls ls')


def handle_ls(debugger, command, result, internal_dict):
    """
    
    implemented in YJLLDB/autoGenerated/ls.py
    """
    if len(command):
        cmd = 'ls ' + command
    else:
        cmd = 'ls'
    code, out, err = util.exe_shell_command(cmd)
    if err or code != 0:
        print(err)

    if out:
        print(out)
    