# -*- coding: UTF-8 -*-

import lldb
import util


def __lldb_init_module(debugger, internal_dict):
    debugger.HandleCommand(
        'command script add -h "" -f '
        'man.handle_man man')


def handle_man(debugger, command, result, internal_dict):
    """
    
    implemented in YJLLDB/autoGenerated/man.py
    """
    code, out, err = util.exe_shell_command('man ' + command)
    if err or code != 0:
        print(err)

    if out:
        print(out)
    