# -*- coding: UTF-8 -*-

import lldb
import util


def __lldb_init_module(debugger, internal_dict):
    debugger.HandleCommand(
        'command script add -h "" -f '
        'sh.handle_sh sh')


def handle_sh(debugger, command, result, internal_dict):
    """
    
    implemented in YJLLDB/autoGenerated/sh.py
    """
    if len(command):
        cmd = 'sh ' + command
    else:
        cmd = 'sh'
    code, out, err = util.exe_shell_command(cmd)
    if err or code != 0:
        print(err)

    if out:
        print(out)
    